HTML structure committ
INF6420/ss22-carolllemieux pull request #3
Opened 2023-05-28 17:16 UTC by carolllemieux

structure added to webpages/ header main section and footer.

2023-06-05 14:39 UTC, axamei requested changes
i don't see a folder with images. is this something missing intentionally?

2023-06-06 16:54 UTC, carolllemieux commented
I have an image folder. I think I made it incorrectly. I went to the github folder in my documents folder and created the image folder. I didn't realize I should make it a different way. I don't quite understand how to fix it so that Github knows the folder is there.

2023-06-06 17:00 UTC, carolllemieux reviewed
I am confused. The things highlighted in red I removed or changed during the HTML assignment process. I don't understand why they are in the document you are seeing. How do I make the changes and resubmit? 

Do I need to merge, then make the changes or do I make the changes and then create a new committ?

2023-06-06 17:08 UTC, carolllemieux reviewed
The index page here is not the one that is on my Visual Code. I don't understand why there is a discrepancy between them. My GitHub doesn't says I have 0 changes.

2023-06-09 20:12 UTC, axamei requested changes
Change the `src` to remove `../ss22-carolllemieux/`. You can use the find/replace tool in VS Code or change the individual HTML files.

2023-06-09 20:12 UTC, axamei commented on contact-me.html
> +                    <img src="../ss22-carolllemieux/images/logocl.PNG" alt="Logo overlapping CL Carol LeMieux's initials" style="width:200px;height:200px;">
Change `src="../ss22-carolllemieux/images/logocl.PNG"` to `src="images/logocl.PNG"`

2023-06-09 20:12 UTC, axamei commented on contact-me.html
> +                    <img src="../ss22-carolllemieux/images/office.jpg" alt="technology office" style="width:600px;height:200px;"></figure>
Change the `src` to remove `../ss22-carolllemieux/`

2023-06-09 20:12 UTC, axamei commented on edtech.html
> +                    <img src="../ss22-carolllemieux/images/logocl.PNG" alt="Logo overlapping CL Carol LeMieux's initials" style="width:200px;height:200px;">
Change the `src` to remove `../ss22-carolllemieux/`

2023-06-09 20:12 UTC, axamei commented on edtech.html
> +                    <img src="../ss22-carolllemieux/images/office.jpg" alt="technology office" style="width:600px;height:200px;"></figure>
Change the `src` to remove `../ss22-carolllemieux/`

2023-06-09 20:12 UTC, axamei commented on index.html
> +                    <img src="../ss22-carolllemieux/images/logocl.PNG" alt="Logo overlapping CL Carol LeMieux's initials" style="width:200px;height:200px;">
Change the `src` to remove `../ss22-carolllemieux/`

2023-06-09 20:12 UTC, axamei commented on index.html
> +                    <img src="../ss22-carolllemieux/images/office.jpg" alt="technology office" style="width:75%;height:200px;"></figure>
Change the `src` to remove `../ss22-carolllemieux/`

2023-06-09 20:12 UTC, axamei commented on mlis.html
> +                    <img src="../ss22-carolllemieux/images/logocl.PNG" alt="Logo overlapping CL Carol LeMieux's initials" style="width:200px;height:200px;">
Change the `src` to remove `../ss22-carolllemieux/`

2023-06-09 20:12 UTC, axamei commented on mlis.html
> +                    <img src="../ss22-carolllemieux/images/office.jpg" alt="technology office" style="width:600px;height:200px;"></figure>
Change the `src` to remove `../ss22-carolllemieux/`

2023-06-09 20:12 UTC, axamei commented on resume.html
> +                <img src="../ss22-carolllemieux/images/logocl.PNG" alt="Logo overlapping CL Carol LeMieux's initials" style="width:200px;height:200px;">
Change the `src` to remove `../ss22-carolllemieux/`

2023-06-09 20:12 UTC, axamei commented on resume.html
> +                <img src="../ss22-carolllemieux/images/office.jpg" alt="technology office" style="width:600px;height:200px;"></figure>
Change the `src` to remove `../ss22-carolllemieux/`

2023-06-09 20:12 UTC, axamei commented on testimonials.html
> +                    <img src="../ss22-carolllemieux/images/logocl.PNG" alt="Logo overlapping CL Carol LeMieux's initials" style="width:200px;height:200px;">
Change the `src` to remove `../ss22-carolllemieux/`

2023-06-09 20:12 UTC, axamei commented on testimonials.html
> +                    <img src="../ss22-carolllemieux/images/office.jpg" alt="technology office" style="width:600px;height:200px;"></figure>
Change the `src` to remove `../ss22-carolllemieux/`

2023-06-11 18:03 UTC, carolllemieux commented
I have corrected the img src code in each file.

2023-06-12 15:23 UTC, axamei approved these changes

2023-06-12 15:24 UTC, merged